language: php
sudo: false

notifications:
    email: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.7.*
        - php: 5.6
          env:
              - SYMFONY_VERSION=2.8.*
        - php: 7.0
          env:
              - SYMFONY_VERSION=3.0.*
        - php: 7.0
        - php: hhvm
        - php: nightly

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - if [[ "$DEPENDENCIES" != "low" && ! $SYMFONY_VERSION ]]; then composer update; fi;
    - if [[ "$DEPENDENCIES" != "low" && $SYMFONY_VERSION ]]; then composer require symfony/symfony:${SYMFONY_VERSION} -n; fi;

script:
    - ./vendor/bin/phpcs --extensions=php --report-full --standard=PSR2 --exclude=Generic.Files.LineLength --ignore=/vendor/ .
    - ./vendor/bin/phpunit --no-coverage
