install:
    - composer install

language: php

notifications:
    email: false

php:
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

script:
    - ./vendor/bin/phpcs --extensions=php --report-full --standard=PSR2 --exclude=Generic.Files.LineLength --ignore=/vendor/ .
    - ./vendor/bin/phpunit --no-coverage

sudo: false
